# Generated by Django 2.2.2 on 2019-07-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
