# Generated by Django 2.2.3 on 2019-08-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_users',
            field=models.ManyToManyField(related_name='comment_like_users', to='server.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(related_name='post_like_users', to='server.User'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_comments',
        ),
        migrations.AddField(
            model_name='user',
            name='like_comments',
            field=models.ManyToManyField(to='server.Comment'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_posts',
        ),
        migrations.AddField(
            model_name='user',
            name='like_posts',
            field=models.ManyToManyField(to='server.Post'),
        ),
    ]
