# Generated by Django 2.2.3 on 2019-08-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190808_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_like_users', to='server.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_like_users', to='server.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_comments',
            field=models.ManyToManyField(blank=True, null=True, to='server.Comment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_posts',
            field=models.ManyToManyField(blank=True, null=True, to='server.Post'),
        ),
    ]
