# Generated by Django 2.2.3 on 2019-08-07 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190807_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_posts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
        migrations.AlterField(
            model_name='post',
            name='major',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='server.Major'),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='server.Major'),
        ),
    ]
